server:
  port: 8090

spring:
  # Keep MVC stack when WebFlux is also on the classpath
  main:
    web-application-type: servlet

  application:
    name: web-ui-service

  thymeleaf:
    cache: false

  jackson:
    serialization:
      write-dates-as-timestamps: false

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ticketing-app
            client-secret: YOUR_CLIENT_SECRET_HERE
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - profile
              - email
        provider:
          keycloak:
            issuer-uri: http://localhost:9090/realms/cydeo-dev
            user-name-attribute: preferred_username

gateway:
  base-url: http://localhost:8762
